version: '3.9'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: postgres_resilience
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gracethd1
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: flask_resilience
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

volumes:
  pgdata:
